### ISSUE TITLE
UndefinedConversionError when rendering compile output to json

### ISSUE THREAD

**Issue by edyst-tech** [judge0/api#100]
Post commit  https://github.com/judge0/api/commit/64635c98f7c0475e33b9b4629a6da8bc20fff60a  we are seeing the following error when rendering submission with C/C++ compile error output.

```ruby
[ActiveJob] [IsolateJob] [d7555d8f-c6dd-480a-8d9b-2192adb546eb] Performed IsolateJob (Job ID: d7555d8f-c6dd-480a-8d9b-2192adb546eb) from Resque(default) in 105.14ms
[active_model_serializers] Rendered SubmissionSerializer with ActiveModelSerializers::Adapter::Attributes (1.21ms)
Completed 500 Internal Server Error in 115ms (ActiveRecord: 5.1ms)



Encoding::UndefinedConversionError ("\xE2" from ASCII-8BIT to UTF-8):

app/controllers/submissions_controller.rb:47:in `create'
```

Here's the compile output text in ascii:
    "compile_output": "main.c:1:1: error: unknown type name 'print'; did you mean 'int'?\n print hello\n ^~~~~\n int\nmain.c:1:1: error: expected '=', ',', ';', 'asm' or '__attribute__' at end of input",

To reproduce, compile a C/C++ program with source code: "print hello" would do it.

**Comment by hermanzdosilovic** [comment]
I cannot reproduce this error with Judge0 IDE: https://ide.judge0.com/?AEYrY9bexZRWFKMdbOL_XFlccUBF.

Are you using `base64_encode=true` when fetching results?

**Comment by edyst-tech** [comment]
No, we are not using base64_encode. We don't see the error with base64_encode.

**Comment by hermanzdosilovic** [comment]
Problem here is that GCC is outputing some non UTF-8 characters which cannot be send in raw JSON format. Solution here is either explore setting some environment variables as you mentioned in the [comment](https://github.com/judge0/api/commit/64635c98f7c0475e33b9b4629a6da8bc20fff60a#commitcomment-34962309) or using `base64_encode` flag.

I don't know how changing env variables in `isolate_job.rb` would affect other languages so I don't wan't to touch that for now. Using `base64_encode` flag is the right way to do it because it will cover scenarios when user is outputing the exact same non UTF-8 characters to stdout. For example, take a look at this code (https://ide.judge0.com/?BQXR). You cannot GET stdout of this code without `base64_encoded` flag set to `true`, nor you cannot set proposed env variables to anything that would cover this case. So, please use `base64_encoded` flag **always**.

**Comment by hermanzdosilovic** [comment]
I have made [asciicast](https://asciinema.org/a/318475) for additional help. Be sure to check it out.
