### ISSUE TITLE
Error Queue is full

### ISSUE THREAD

**Issue by nguyenvanquan7826** [judge0/api#102]
Hi, Api reponse error:

```
[Response 9/17/2019, 5:52:53 PM] 503 error
{
    "readyState": 4,
    "responseText": "{\"error\":\"queue is full\"}",
    "responseJSON": {
        "error": "queue is full"
    },
    "status": 503,
    "statusText": "error"
}
```

**Comment by hermanzdosilovic** [comment]
Hi,

this is a new feature in Judge0 API since v1.3.0 (
https://github.com/judge0/api/releases/tag/v1.3.0). Documentation is also
updated and includes information about this (
https://api.judge0.com/#submissions-submission-post).

Currently MAX_QUEUE_SIZE is set to 100. This means that if queue is full
then your submission request will be rejected.

I would suggest that you dont create so much submissions in small time
frame. I.e. lower submission create frequency.

**Comment by nguyenvanquan7826** [comment]
But I test on dummy page and it also this error.

**Comment by hermanzdosilovic** [comment]
It doesn't matter where the request is coming from. MAX_QUEUE_SIZE is 100 and if the queue is full and you create a new submission then that submission will be rejected until the queue is the size < MAX_QUEUE_SIZE.
