### ISSUE TITLE
Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by noisytoken** [judge0/api#105]
Hi

I am using postgresql with my application. It looks like the Judgle API is also using it.

Trying to start dev shell  when postgresql is running, results in the following error:

```bash
ERROR: for judge0-dev-db  Cannot start service db: b'driver failed programming external connectivity on endpoint judge0-dev-db (4482f29b48f9141c1e4ae0ee91824d3432ee94e9ec4e9375Starting judge0-dev-api ... done
 already in use'

ERROR: for db  Cannot start service db: b'driver failed programming external connectivity on endpoint judge0-dev-db (4482f29b48f9141c1e4ae0ee91824d3432ee94e9ec4e9375807f68b8e6b7fa55): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use'
ERROR: Encountered errors while bringing up the project.
```

**Comment by singh-shreya6** [comment]
Hi,
I encountered the same problem. You can simply change the port number for Postgresql in docker-compose.dev.yml. It will start working.

**Comment by hermanzdosilovic** [comment]
Hey @noisytoken,

you are seeing this error because some other app on your PC is using port 5432. You should either stop that app and run Judge0 API again, or as @singh-shreya6 suggested change the port number on the left side in the `docker-compose.dev.yml` file from `5432` to `5433` for example.

Let me know if I can help you more on this issue.
