### ISSUE TITLE
Feature request: response_base64_encoded param for submission API (or better non-ascii support)

### ISSUE THREAD

**Issue by daisy1754** [judge0/api#130]
When I try submissions with non-ASCII character, it failed with 500

Example request (with judge0 1.4.0):
URL: `/submissions?wait=true`
Param: `{"language_id":38,"source_code":"puts \"あ\""}`

(In server side log I see `Encoding::UndefinedConversionError ("\xE3" from ASCII-8BIT to UTF-8)`)

There is base64_encoded parameter but it expects both input and output are bae64 encoded. So following still didn't work
URL: `submissions?wait=true&base64_encoded=true`
Param: `{"language_id":38,"source_code":"puts \"あ\""}`

Response: 
```
{
  "stdout": null,
  "time": "0.045",
  "memory": 4460,
  "stderr": "bWFpbi5yYjoxOiBpbnZhbGlkIG11bHRpYnl0ZSBjaGFyIChVVEYtOCkK\n",
  "token": "b5ea11bc-4e23-4880-8174-2c963666f708",
  "compile_output": null,
  "message": "RXhpdGVkIHdpdGggZXJyb3Igc3RhdHVzIDE=\n",
  "status": {
    "id": 11,
    "description": "Runtime Error (NZEC)"
  }
}
```

Feature request 1:
Can new parameter `response_base64_encoded` be added to submission API so we can pass input as UTF-8 string but still properly encode output

Feature request 2: 
Can judge0 handle UTF-8 in both input and output w/o requiring specific parameters?

**Comment by hermanzdosilovic** [comment]
Hi @daisy1754,

as of [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01) you will get nice error description when submission serialization fails on the server side.

What you should always do is use `base64_encoded=true` flag because you don't know when submission will cause serialization errors. With this flag you are guaranteed to successfully get all submission attributes you requested.

**Comment by hermanzdosilovic** [comment]
I have made [asciicast](https://asciinema.org/a/318475) for additional help. Be sure to check it out.
