### ISSUE TITLE
System configuration

### ISSUE THREAD

**Issue by njsrinivas** [judge0/api#144]
We want to use Judge0 API for 1000 users, simultaneously submit their code. Can anyone please suggest hardware configuration and judge0-api.conf settings to achieve the same. We are using Intel Xeon E5-2650 v4 2.20GHz CPU(12 cores, 24 threads) with 16GB RAM.  We know this is not a bug but want to find the judge0-api.conf settings as there is no proper documentation for optimization. If required we can procure CPU with higher cores and RAM. Thanks in advance.

**Comment by hermanzdosilovic** [comment]
Hi @njsrinivas,

since there is currently no official documentation that explains how to scale Judge0 API we can arrange a call where I can explain in detail how to scale it for this number of users. Until then, please read following issues: https://github.com/judge0/api/issues/118, https://github.com/judge0/api/issues/114.

Let me know (by email) if you want to have a call and quick session where I can explain in detail how to achieve this.

For everybody else, please be patient, I am doing my best in writing a detailed documentation for this along side with regular releases and support.

**Comment by hermanzdosilovic** [comment]
Hi @njsrinivas,

you can [schedule a meeting](https://judge0.appointlet.com/) with me so we can discuss this.
