### ISSUE TITLE
Multiple source code files

### ISSUE THREAD

**Issue by hujaepa** [judge0/api#162]
Hi, I'm just wondering if this API supports multiple source code files submission? For example in Java programming that involve with multiple classes? In this case, does the API able to cater it?

**Comment by hermanzdosilovic** [comment]
Hi @hujaepa,

Since Judge0 API v1.6.0 (unreleased yet) you will be able to send additional files alongside with your program. The problem is that for case like Java and other compiled languages I would need to compile all java files that are inside the sandbox and not just `Main.java`. So for now, this is not possible for your use-case.

Either way, please take a look at this feature with additional files: https://asciinema.org/a/318548

**Comment by hujaepa** [comment]
Ok, noted with thanks
