### ISSUE TITLE
Concatenating two simple strings in Python generates WA

### ISSUE THREAD

**Issue by hugox14** [judge0/api#208]
Hi guys, I have a simple Python code:

```
a = input()
b = input()
print(a+b)
```
Input:
```
Hello
World
```
Expected Output:
```
HelloWorld
```
When I create a submission I get WA:
```
{
    "source_code": "a = input()\r\nb = input()\r\nprint(a+b)",
    "language_id": 71,
    "stdin": "Hello\r\nWorld",
    "expected_output": "HelloWorld",
    "stdout": "Hello\rWorld\n",
    "status_id": 4
}
```
The input, source code and expected output I get from a mysql database and call the API from pure PHP. What do you think could be the problem?

**Comment by hermanzdosilovic** [comment]
As I can see this is because your input contains character `\r` from the first line which is unique for Windows. On windows newline is represented as `\r\n` while on Unix it is `\n` and it seems that Python does not strip that with `input()`. You should change your code to `input().rstrip()` and it should work, or trim the input before. This is not Judge0 problem.
