### ISSUE TITLE
Not able to pull judge0 api code

### ISSUE THREAD

**Issue by piyushkhandelwal993** [judge0/api#4]
I am trying to pull judge0 api source code but after few pulls it gives authentication required error and terminates. 

I have tried it several times.

I have attached the screenshot for the same.
![screen shot 2017-03-31 at 8 16 13 am](https://cloud.githubusercontent.com/assets/1552286/24534549/527a4580-15ec-11e7-8f8a-85ee6eb49429.png)

**Comment by hermanzdosilovic** [comment]
Hi @piyushkhandelwal993,

I don't think this is an Judge0 API issue, but rather hub.docker.com issue or your network connection issue.
Please try again few more times, I don't know how else I can help you.

If this issue is still present for you then you can try building Judge0 API on your own:

1. Clone https://github.com/judge0/api-base repository
2. Build API Base image: `docker build -t judge0/api-base:0.1.1 .`
3. Clone https://github.com/judge0/api repository
4. Build API image: `docker build -t judge0/api:0.1.1 .`
