### ISSUE TITLE
Java Main class

### ISSUE THREAD

**Issue by aditya999goel** [judge0/api#59]
Currently java program compiles only if it has "Main" class. Can you check this?

**Comment by hermanzdosilovic** [comment]
Hey @aditya999goel,

You are right. Java program compiles only if it has `Main` class that has `main` function in it.

This is because I save your Java program in the file called `Main.java` and in the Java world you should name your classes in the same way your files are called.

I cannot make exception here for Java to allow you calling your classes the way you would like, because I then won't have unified way of processing the submissions.
