### ISSUE TITLE
Wait not allowed

### ISSUE THREAD

**Issue by nguyenvanquan7826** [judge0/api#61]
Hi, today api have an issue: wait not allowed. Please check it. Thank you!
Bellow is response when run:
```
[Response 2/1/2019, 9:49:20 AM] 400 error
{
    "readyState": 4,
    "responseText": "{\"error\":\"wait not allowed\"}",
    "responseJSON": {
        "error": "wait not allowed"
    },
    "status": 400,
    "statusText": "error"
}

[DONE 2/1/2019, 9:49:20 AM]
```

**Comment by hermanzdosilovic** [comment]
Hi @nguyenvanquan7826,

I had to turn off that feature because instance on Digital Ocean that I have had CPU usage on 100% almost 3 times a week which resulted that Judge0 API was not available for few hours then.

Sorry but currently I cannot enable this feature anymore, it is causing too much trouble for public use.

Sometime in the future I will setup Patreon account where people could donate to development in Judge0 and then I could have much bigger instances that could probably solve this issue.

**Comment by nguyenvanquan7826** [comment]
ah, thank you!

**Comment by sagardesai90** [comment]
I am seeing this issue, was it something that was resolved previously and has now arisen again?

**Comment by hermanzdosilovic** [comment]
This feature is not enabled in the https://api.judge0.com nor on the [RapidAPI](https://rapidapi.com/hermanzdosilovic/api/judge0). Please read the [docs](https://api.judge0.com/#submissions-submission-post) for more details.

**Comment by hariharandr** [comment]
can we get this "wait" feature on the pro version? Coz, I wonder what happens if we pass a complicated program and that takes a bit to return the result? I don't have a solution to await for the response. Or when to check back again. Should I just keep calling on some interval for the result?
